# Generated by Django 5.1.1 on 2024-10-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CASUAL', 'Casual'), ('DRESSES', 'Dresses'), ('UNDERWEAR', 'Underwear'), ('TOP_TEES', 'Top and Tees'), ('JEANS', 'Jeans'), ('SPORTSWEAR', 'Sportswear'), ('SWIMSUIT', 'Swimsuit'), ('OTHERS', 'Others')], default='OTHERS', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
