# Generated by Django 5.1.1 on 2024-11-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesproduct',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='products.clothesproduct'),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='other_images',
            field=models.ManyToManyField(blank=True, to='products.productimage'),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='sizes_available',
            field=models.ManyToManyField(blank=True, to='products.productsize'),
        ),
    ]
