# Generated by Django 5.1.1 on 2024-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesproduct',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
