# Generated by Django 5.1.1 on 2024-10-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_clothesproduct_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CASUAL', 'Casual'), ('DRESSES', 'Dresses'), ('UNDERWEAR', 'Underwear'), ('TOP_TEES', 'Top and Tees'), ('JEANS', 'Jeans'), ('SPORTSWEAR', 'Sportswear'), ('SWIMSUIT', 'Swimsuit'), ('OTHERS', 'Others')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/other_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='clothesproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clothesproduct',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=6),
        ),
        migrations.AlterField(
            model_name='clothesproduct',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='categories',
            field=models.ManyToManyField(to='products.category'),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='other_images',
            field=models.ManyToManyField(blank=True, to='products.productimage'),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='sizes_available',
            field=models.ManyToManyField(blank=True, to='products.productsize'),
        ),
    ]
