# Generated by Django 5.1.1 on 2024-10-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_vendor'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesproduct',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('DRESSES', 'Dresses'), ('UNDERWEAR', 'Underwear'), ('TOP_TEES', 'Top and Tees')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
    ]
