# Generated by Django 5.1.1 on 2024-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_delete_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organization', models.CharField(max_length=30)),
                ('rating', models.PositiveIntegerField(blank=True, default=0)),
                ('address', models.CharField(max_length=100)),
                ('total_sales', models.IntegerField(blank=True, default=0)),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='product_in_stock', to='products.clothesproduct')),
            ],
        ),
    ]
